/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/webhooks/authentik": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthCheck"];
        put?: never;
        post: operations["handleAuthentikEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addVideo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["home"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/{queueJobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthentikEventRequest: {
            action?: string;
            user?: components["schemas"]["AuthentikUser"];
        };
        AuthentikUser: {
            uuid?: string;
            username?: string;
            name?: string;
            email?: string;
            /** Format: date-time */
            date_joined?: string;
            /** Format: date-time */
            last_updated?: string;
            /** Format: date-time */
            last_login?: string;
        };
        AddVideoRequest: {
            videoId?: string;
        };
        CommandAcceptedResponse: {
            /** Format: uuid */
            queueJobId?: string;
        };
        AddChannelRequest: {
            channelId?: string;
        };
        GetProgressResponse: {
            queueJob?: components["schemas"]["QueueJob"];
            events?: components["schemas"]["QueueJobEvent"][];
            childQueueJobs?: components["schemas"]["GetProgressResponse"][];
        };
        QueueJob: {
            /** Format: uuid */
            id?: string;
            parentJob?: components["schemas"]["QueueJob"];
            /** @enum {string} */
            type?: "FETCH_PLATFORM_CONTENT" | "FETCH_CHANNEL_METADATA" | "FETCH_VIDEO_METADATA";
            /**
             * @description Queue job status.
             *
             *     - `QUEUED` — row exists and message should be processed
             *     - `RUNNING` — worker picked it up
             *     - `COMPLETED` — work succeeded
             *     - `FAILED` — work failed permanently
             *     - `CANCELED` — user/system canceled it
             * @enum {string}
             */
            status?: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELED";
            payload?: {
                [key: string]: Record<string, never>;
            };
            requestedBy?: components["schemas"]["User"];
            correlationKey?: string;
            dedupeKey?: string;
            errorType?: string;
            errorMessage?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        QueueJobEvent: {
            /** Format: uuid */
            id?: string;
            job?: components["schemas"]["QueueJob"];
            /**
             * @description Queue job status.
             *
             *     - `QUEUED` — row exists and message should be processed
             *     - `RUNNING` — worker picked it up
             *     - `COMPLETED` — work succeeded
             *     - `FAILED` — work failed permanently
             *     - `CANCELED` — user/system canceled it
             * @enum {string}
             */
            status?: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELED";
            message?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        User: {
            /** Format: uuid */
            id?: string;
            username?: string;
            displayName?: string;
            email?: string;
            /** Format: date-time */
            dateJoined?: string;
            /** Format: date-time */
            lastUpdated?: string;
            /** Format: date-time */
            lastLogin?: string;
            verified?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    handleAuthentikEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthentikEventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addVideo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddVideoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommandAcceptedResponse"];
                };
            };
        };
    };
    addChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddChannelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommandAcceptedResponse"];
                };
            };
        };
    };
    home: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                queueJobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetProgressResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: {
                            name?: string;
                        };
                    };
                };
            };
        };
    };
}
