/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/webhooks/authentik": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthCheck"];
        put?: never;
        post: operations["handleAuthentikEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/{queueJobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/command/{commandId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteCommand"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthentikEventRequest: {
            action?: string;
            user?: components["schemas"]["AuthentikUser"];
        };
        AuthentikUser: {
            uuid?: string;
            username?: string;
            name?: string;
            email?: string;
            /** Format: date-time */
            date_joined?: string;
            /** Format: date-time */
            last_updated?: string;
            /** Format: date-time */
            last_login?: string;
        };
        AddChannelRequest: {
            channelId?: string;
        };
        CommandAcceptedResponse: {
            /** Format: uuid */
            queueJobId?: string;
        };
        GetProgressResponse: {
            progress: components["schemas"]["Progress"];
        };
        Progress: {
            /** Format: uuid */
            id: string;
            /**
             * @description Queue job status.
             *
             *     - `QUEUED` — row exists and message should be processed
             *     - `RUNNING` — worker picked it up
             *     - `COMPLETED` — work succeeded
             *     - `FAILED` — work failed permanently
             *     - `CANCELED` — user/system canceled it
             * @enum {string}
             */
            latestStatus: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELED";
            events: components["schemas"]["ProgressStatusEvent"][];
            childProgresses: components["schemas"]["Progress"][];
        };
        ProgressStatusEvent: {
            /** Format: uuid */
            id: string;
            message: string;
            /**
             * @description Queue job status.
             *
             *     - `QUEUED` — row exists and message should be processed
             *     - `RUNNING` — worker picked it up
             *     - `COMPLETED` — work succeeded
             *     - `FAILED` — work failed permanently
             *     - `CANCELED` — user/system canceled it
             * @enum {string}
             */
            status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELED";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    handleAuthentikEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthentikEventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddChannelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommandAcceptedResponse"];
                };
            };
        };
    };
    getProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                queueJobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetProgressResponse"];
                };
            };
        };
    };
    deleteCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
